### ISSUE TITLE
after refreshing script stops when tatkal time starts

### ISSUE THREAD

**Issue by sudhanshu947** [dpak-maurya/irctc-tatkal-ticket-booking#8]
1. when i logging before tatkal time it loads for few times and stops and it doesn't work to bypass we can do that script will wait till 10:00 & 11:00 then it can click availability button

2. we can add option if only confirm birth allotted

**Comment by dpak-maurya** [comment]
@sudhanshu947 thanks for pointing that issue. 

1. When the script runs, it attempts to click the "Book Now" button as soon as it is not disabled. The script checks the availability of the button every 5 seconds (refresh interval) by realoading the selected class(i.e. SL, 3A). When the "Book Now" button first becomes available, the script clicks it. However, it is unable to proceed due to an IRCTC error message, such as "Operation not allowed" (possibly due to clicking too early). As a result, the script halts on that page, requiring manual intervention to proceed. I will consider your suggestions and, if they work, will update the script accordingly.
2. i will add this feature for if only confirm birth allotted

**Comment by sudhanshu947** [comment]
> @sudhanshu947 thanks for pointing that issue. 
> 
> 
> 
> 1. When the script runs, it attempts to click the "Book Now" button as soon as it is not disabled. The script checks the availability of the button every 5 seconds (refresh interval) by realoading the selected class(i.e. SL, 3A). When the "Book Now" button first becomes available, the script clicks it. However, it is unable to proceed due to an IRCTC error message, such as "Operation not allowed" (possibly due to clicking too early). As a result, the script halts on that page, requiring manual intervention to proceed. I will consider your suggestions and, if they work, will update the script accordingly.
> 
> 2. i will not be able add this feature because this option if only confirm birth allotted have been removed from irctc passenger page
> 
>     
There is option for if only confirm birth allotted this option is only available if train has available seats before booking you can check it out once

**Comment by brupadhyay** [comment]
@dpak-maurya manual intervention meaning do we just need to close the error message or do the whole process by ourselves?
Asking cuz today I got the error as ```Unable to perform the transaction, please try again```

**Comment by sudhanshu947** [comment]
> Unable to perform the transaction, please try again

**Unable to perform the transaction, please try again**

This error occurs only when we try to login or try to book tickets frequently on irctc and it blocks our ip as much i had researched well I'll  share more details soon let me collect some more info first...

**Comment by sudhanshu947** [comment]
> @sudhanshu947 @dpak-maurya can you provide some tips from your side, cause today I got **booking not allowed, try again** error, also I think the refresh time of 5 sec may cause high request rate and from 2 days I saw till **10:00:30** the book now button doesn't gets enabled, I'm not booking for my benefits but seriously, I want confirmation for my family members

Sure give me sometime till then and if you want you can message me on WhatsApp here its ‪**+917518330267‬**

**Comment by dpak-maurya** [comment]
@sudhanshu947 i have updated the start timer from 10:59:45 to 10:59:53 so that number of refresh click become less. I have tested with this configuration it's working fine and going to next page. you can check from your side if it's working now.
